### PR TITLE
Suggest using the WithCancellation extension method

### PR DESCRIPTION
**Pull request by AArnott**

### CODE REVIEW

**Comment by slang25** [comment]
I really feel that for more people to adopt this, it needs to be moved into a library that doesn't have VisaulStudio in the name, I know this issue was closed a while back, but there's enough useful stuff now that a focus should be made on reducing barriers to adoption. 🙏

**Comment by AArnott** [comment]
@slang25 I guess you're talking about https://github.com/Microsoft/vs-threading/issues/193?

**Comment by AArnott** [comment]
@slang25 I guess you're talking about https://github.com/Microsoft/vs-threading/issues/193?

**Comment by davidfowl** [comment]
AArnot, file this on corefx

**Comment by AArnott** [comment]
@davidfowl What exactly are you proposing I file? A request for the extension method to be defined?

**Comment by davidfowl** [comment]
I'm suggesting this is a good method that's so commonly used that it should probably be somewhere in the BCL. I don't want to point to vs-threading as the go-to library for async helpers. This document will be migrated to the official ASP.NET Core and .NET Core docs.

**Pull request closed without merging**
