### PR TITLE
Change Task to ValueTask in ConcurrentDictionary.GetOrAdd example

### PR DESCRIPTION
**Pull request by dalibormesaric**
I copy/pasted the examples and got compiler errors. Then I checked FindAsync signature, and it expects ValueTask instead of Task, so I thought I could update the document,

https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbcontext.findasync?view=efcore-6.0

### CODE REVIEW

**Comment by davidfowl** [comment]
See https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/pull/75#discussion_r702910191

**Comment by davidfowl** [comment]
How does ValueTask\<T\> help here?

**Comment by dalibormesaric** [comment]
It just makes it so that the code in the example compiles. But I learned that there is also FindAsync.AsTask() so I can modify my PR to that.

**Comment by davidfowl** [comment]
Why would we change it to a ValueTask?

**Comment by dalibormesaric** [comment]
You don't have to change it to ValueTask, it will work with FindAsync().AsTask() instead.

Here is what I'm talking about:

c/p example
image
with ValueTask
image
with .AsTask()
image

**Comment by davidfowl** [comment]
Got it, you have a method that didn;t return ValueTask, I understand now. Using AsTask makes sense there. I think we can close this.

**Pull request closed without merging**
